In [2]:
import pandas as pd

pov_url = 'https://data.wprdc.org/dataset/c6265ffb-c86e-4a2c-870b-1aaa0772c449/resource/7996d143-c155-466e-8414-115f74997dd7/download/poverty-status-of-individuals-in-the-past-12-months-by-living-arrangement.csv';
pop_url = 'https://data.wprdc.org/dataset/95af9f2c-61c8-446b-ae72-852e195684f3/resource/a8414ed5-c50f-417e-bb67-82b734660da6/download/preliminarycitypittsburghneighborhood_pl94171summary-2.csv'
path = '/Users/benorr/Documents/Big Ideas/agg_income.csv'

income = pd.read_csv(path)
poverty = pd.read_csv(pov_url)
population = pd.read_csv(pop_url)
poverty.rename(columns={'Estimate; Income in the past 12 months below poverty level:': 'income_12mo_below_pov'}, inplace=True)
income.rename(columns={'Estimate; Aggregate household income in the past 12 months (in 2014 Inflation-adjusted dollars)': 'agg_income_past_12mo'}, inplace=True)

income.head()

,Neighborhood,Id,agg_income_past_12mo,Margin of Error; Aggregate household income in the past 12 months (in 2014 Inflation-adjusted dollars)
0,Allegheny Center,1,28265700,8176700
1,Allegheny West,2,23755400,15159354
2,Allentown,3,40566300,8358735.28
3,Arlington,4,33111400,6248592.971
4,Arlington Heights,5,2515000,1056475

In [3]:
poverty.head(25)

,Neighborhood,Id,Estimate; Total:,Margin of Error; Total:,income_12mo_below_pov,Margin of Error; Income in the past 12 months below poverty level:,Estimate; Income in the past 12 months below poverty level: - In family households:,Margin of Error; Income in the past 12 months below poverty level: - In family households:,Estimate; Income in the past 12 months below poverty level: - In family households: - In married couple families:,Margin of Error; Income in the past 12 months below poverty level: - In family households: - In married couple families:,...,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement:,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement:,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder:,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder:,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Living alone,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Living alone,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Not living alone,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Not living alone,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Other living arrangement,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Other living arrangement
0,Allegheny Center,1,1130.0,184.000000,516.0,195.000000,290.0,202.000000,163.0,195.000000,...,471.0,113.000000,375.0,85.000000,309.0,80.000000,66.0,38.000000,96.0,57.000000
1,Allegheny West,2,331.0,104.000000,45.0,26.000000,0.0,10.000000,0.0,10.000000,...,87.0,40.000000,79.0,36.000000,66.0,34.000000,13.0,13.000000,8.0,11.000000
2,Allentown,3,2624.0,499.013026,750.0,397.315995,490.0,400.251171,0.0,17.320508,...,394.0,136.638208,328.0,105.877287,274.0,98.208961,54.0,54.083269,66.0,56.964901
3,Arlington,4,1890.0,367.887211,343.0,160.626897,279.0,158.776573,97.0,96.046864,...,434.0,172.565929,230.0,71.679844,125.0,51.855569,105.0,49.608467,204.0,117.635029
4,Arlington Heights,5,380.0,196.000000,278.0,198.000000,257.0,196.000000,0.0,10.000000,...,47.0,38.000000,47.0,38.000000,47.0,38.000000,0.0,10.000000,0.0,10.000000
5,Banksville,6,3944.0,494.205423,252.0,175.835150,178.0,166.979041,118.0,152.983659,...,1218.0,260.618495,1057.0,228.155649,891.0,231.775754,166.0,80.950602,161.0,90.493094
6,Bedford Dwellings,7,1169.0,169.000000,815.0,196.000000,566.0,201.000000,113.0,133.000000,...,157.0,60.000000,152.0,59.000000,152.0,59.000000,0.0,10.000000,5.0,8.000000
7,Beechview,8,8081.0,751.370082,1473.0,435.621395,1146.0,428.893926,392.0,319.713935,...,1478.0,266.951306,1243.0,207.985576,994.0,180.244279,249.0,111.897274,235.0,109.799818
8,Beltzhoover,9,1885.0,337.761750,554.0,210.964452,323.0,191.319105,0.0,20.000000,...,209.0,74.040529,188.0,67.609171,184.0,67.609171,4.0,19.519221,21.0,29.866369
9,Bloomfield,10,8702.0,527.937496,1760.0,316.794886,392.0,189.881542,175.0,134.621692,...,3621.0,347.547119,2592.0,212.497059,1826.0,190.908355,766.0,142.355190,1029.0,211.135028
10,Bluff,11,630.0,136.370818,215.0,111.180034,11.0,24.269322,0.0,20.000000,...,228.0,92.660671,122.0,62.008064,95.0,55.901699,27.0,29.748950,106.0,65.954530
11,Bon Air,12,832.0,175.000000,140.0,167.000000,133.0,167.000000,0.0,10.000000,...,121.0,68.000000,106.0,60.000000,89.0,55.000000,17.0,18.000000,15.0,16.000000
12,Brighton Heights,13,7249.0,524.816158,945.0,307.276748,613.0,289.780952,157.0,119.394305,...,1353.0,224.908870,1102.0,174.991428,920.0,162.640708,182.0,70.992957,251.0,95.801879
13,Brookline,14,13191.0,916.330181,1361.0,342.595972,972.0,318.667538,421.0,243.803199,...,2593.0,324.973845,2258.0,280.023213,1910.0,261.317814,348.0,138.224455,335.0,113.635382
14,California-Kirkbride,15,786.0,206.000000,305.0,120.000000,223.0,118.000000,9.0,14.000000,...,87.0,45.000000,62.0,26.000000,48.0,22.000000,14.0,18.000000,25.0,26.000000
15,Carrick,16,10045.0,789.566970,1993.0,499.746936,1475.0,483.259765,361.0,226.453086,...,1748.0,292.145512,1432.0,217.740671,1161.0,188.719368,271.0,121.922106,316.0,131.015266
16,Central Business District,17,2655.0,344.151130,533.0,186.086002,59.0,66.128662,29.0,47.581509,...,1396.0,262.009542,1196.0,213.398688,1040.0,206.434009,156.0,85.936023,200.0,113.022122
17,Central Lawrenceville,18,4356.0,362.133953,664.0,195.417502,306.0,159.367500,134.0,112.876038,...,1521.0,254.841127,1063.0,151.555270,650.0,120.120773,413.0,108.871484,458.0,136.180028
18,Central Northside,19,2891.0,335.806492,908.0,291.111662,626.0,285.987762,111.0,99.015150,...,1030.0,195.430294,807.0,116.803253,625.0,100.169856,182.0,68.833132,223.0,112.569978
19,Central Oakland,20,5064.0,562.983126,3505.0,518.957609,187.0,134.320512,32.0,51.961524,...,1064.0,228.648201,600.0,127.114122,306.0,98.524109,294.0,94.175368,464.0,150.804509
20,Chartiers City,21,414.0,136.000000,62.0,46.000000,39.0,43.000000,0.0,10.000000,...,71.0,58.000000,71.0,58.000000,71.0,58.000000,0.0,10.000000,0.0,10.000000
21,Chateau,22,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
22,Crafton Heights,23,3732.0,320.224921,804.0,229.072041,556.0,226.883230,23.0,30.413813,...,660.0,138.614574,456.0,83.671979,327.0,73.300750,129.0,57.905095,204.0,79.711982
23,Crawford-Roberts,24,2146.0,349.051572,930.0,279.508497,531.0,251.563113,91.0,149.335193,...,476.0,135.532284,448.0,132.003788,424.0,130.598622,24.0,24.839485,28.0,30.675723
24,Duquesne Heights,25,2555.0,357.617114,405.0,242.923856,229.0,221.794950,178.0,213.243992,...,553.0,147.275253,414.0,95.000000,326.0,81.835200,88.0,58.523500,139.0,84.534017

In [4]:
merged_data = pd.merge(population[['Neighborhood', "2020_Total_Population"]],  # Select columns from population
                       poverty[['Neighborhood', 'income_12mo_below_pov']],  # Select columns from income
                       on='Neighborhood',  # Merge on 'Neighborhood' column
                       how='inner')  # Use inner join to only include neighborhoods present in all datasets

# Merge with population dataset
merged_data = pd.merge(merged_data,
                       income[['Neighborhood', 'agg_income_past_12mo']],
                       on='Neighborhood',
                       how='inner')

merged_data.head()

,Neighborhood,2020_Total_Population,income_12mo_below_pov,agg_income_past_12mo
0,Allegheny Center,1419,516.0,28265700
1,Allegheny West,540,45.0,23755400
2,Allentown,2305,750.0,40566300
3,Banksville,4127,252.0,141719200
4,Bedford Dwellings,1386,815.0,8979700